# -*- coding: utf-8 -*-
"""Test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RpEXCUrPlVorWyvs7lHNiazccmNcbVhC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import plotly.express as px
import warnings as ws
ws.defaultaction = "ignore"

# загрузка данных
df = pd.read_csv('/content/drive/MyDrive/dataset_tk.csv', parse_dates = True)
print(df.info())

df.rename(columns={"Unnamed: 0":"Date"},inplace=True)
df['Date']=pd.to_datetime(df["Date"],dayfirst=True)
df.head()

rows, cols = df.shape

print(f"В датасете {cols} колонки и {rows} строки")

df.columns

df.head(10)

df.tail(5)

# df.describe(include=['float', 'int'])
df.describe()

dtype_counts = df.dtypes.value_counts() #подсчет количества столбцов каждого типа данных.
print(f'всего столбцов разных типов - {len(dtype_counts)}')

df.isnull().sum()

mean_temprature = df.mean().sort_values(ascending=False).reset_index().rename(columns = {"index": "State", 0 : "Average Consumption"})
state_code = ['MH', 'GJ', 'UP', 'TN', 'RJ', 'MP', 'KA', 'TG', 'AP', 'PH', 'WB', 'HR', 'CT', 'DL', 'BR', 'OR', 'KL', 'J&K', 'UK', 'HP', 'AS', 'JH', 'DNH', 'GA', 'PY', 'ML', 'CH', 'TR', 'MN', 'NL', 'AR', 'MZ', 'SK']
mean_temprature.state = state_code

plt.figure(figsize = (40,40))
sns.barplot(x= "State", y = "Average Consumption", data = mean_temprature)
plt.show()

df['Maharashtra'].unique()

len(df['Maharashtra'].unique())

df['Maharashtra'].value_counts()

plt.figure(figsize=(16,8))
plt.plot(df.Date,df.Maharashtra)

plt.figure(figsize=(16,8))
plt.title('Power consumption in Maharashtra')
plt.hist(df.Gujarat)

power = df.drop( df.index[137:467] )
power

month = power.groupby(power['Date'].dt.strftime('%B')).sum()

month

#Месячное потребление э/э
plt.figure(figsize=(16,8))
plt.title('Power consumption of states monthly')
sns.heatmap(month)

#Сравнение по двум штатам
plt.figure(figsize=(16,8))
plt.plot(month.Delhi, marker = 'o');
plt.plot(month.Maharashtra , marker = 's');

plt.xlabel('Month')
plt.ylabel('Monthly consumption of power')

plt.title("Comparison")
plt.legend(['Delhi' , 'Maharashtra']);