# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wLstiSOxn0Ue3PXj3WhLiJUwWylf3-Zy
"""

import numpy as np

A = np.matrix ([6, -8, 3])

B = np.matrix([[1], [1], [4]])

A * B

C = np.matrix ([[-3, -7],
                [-10, 6],
                [0, -6],
                [-1, -3]])

D = np.matrix ([[-8, 9],
                [4, -2]])

C * D